AWSTemplateFormatVersion: "2010-10-09"
Description: "Beyonity AWS Infrastructure"

Resources:
  BeyonityBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "beyonity-test-cicd-bucket"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref BeyonityBucket